-- Migration unit 1: schema_changes
-- Transaction mode: transactional
-- Boundary reason: default

CREATE TABLE public.group_invites (
  id         bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  inviter_id bigint                   NOT NULL,
  invitee_id bigint                   NOT NULL,
  group_id   bigint                   NOT NULL
);

ALTER PUBLICATION supabase_realtime ADD TABLE public.group_invites;

ALTER TABLE public.group_invites
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.group_invites
  ADD CONSTRAINT group_invites_pkey PRIMARY KEY (id);

CREATE TABLE public.group_members (
  group_id  bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id   bigint                   NOT NULL,
  joined_at timestamp with time zone DEFAULT now() NOT NULL,
  role      text                     DEFAULT 'member'::text NOT NULL
);

ALTER TABLE public.group_members
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.group_members
  ADD CONSTRAINT group_members_pkey PRIMARY KEY (group_id, user_id);

CREATE TABLE public.groups (
  id          bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_by  bigint                   NOT NULL,
  created_at  timestamp with time zone DEFAULT now() NOT NULL,
  name        text,
  description text
);

ALTER TABLE public.groups
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.groups
  ADD CONSTRAINT groups_pkey PRIMARY KEY (id);

CREATE TABLE public.schedule_blocks (
  id          bigint                 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id     bigint                 NOT NULL,
  day_of_week smallint,
  start_time  time without time zone,
  end_time    time without time zone,
  block_type  text,
  label       text
);

ALTER TABLE public.schedule_blocks
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.schedule_blocks
  ADD CONSTRAINT schedule_blocks_pkey PRIMARY KEY (id);

CREATE TABLE public.users (
  id            bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  username      text                     NOT NULL,
  password_hash text,
  created_at    timestamp with time zone,
  timezone      smallint                 DEFAULT '-4'::smallint NOT NULL
);

ALTER TABLE public.users
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.users
  ADD CONSTRAINT users_name_key UNIQUE (username);

ALTER TABLE public.users
  ADD CONSTRAINT users_pkey PRIMARY KEY (id);